### ISSUE TITLE
Manuális kód átvizsgálás + Statikus analízis

### ISSUE THREAD

**Issue by rhalm** [BME-MIT-IET/iet-hf2021-heekk#1]
Manuális kód átvizsgálás elvégzése az alkalmazás egy részére (GitHub) + Statikus analízis eszköz futtatása és jelzett hibák átnézése (SonarQube)

"Mivel az eszközök rengeteg hibát és figyelmeztetést találhatnak, ezért elég azok egy részét megvizsgálni és ha a csapat minden tagja egyetért vele, akkor javítani. Törekedjetek arra, hogy különböző típusú, és lehetőleg nem triviális hibajelzéseket vizsgáljatok meg."

**Comment by AnKa0** [comment]
A manuális kód átvizsgálás elvégzésehez készítsünk egy strukturált ellenőrző listát

**Comment by AnKa0** [comment]
A formázás ellenőrzésére kereshetnénk egy eszközt

**Comment by AnKa0** [comment]
> @rhalm A manuális kód átvizsgálás elvégzésehez készítsünk egy strukturált ellenőrző listát

Egy vázlatot csináltam, az erre a projektre nézve irreleváns részeket majd ki lehet törölni.

**Comment by rhalm** [comment]
> Egy vázlatot csináltam, az erre a projektre nézve irreleváns részeket majd ki lehet törölni.

Köszi, @AnKa0! Legközelebb a commit messagedhez linkeld be ezt az issue-t, hogy könnyű legyen követni.

**Comment by rhalm** [comment]
Kijavítottam a hibákat, csökkentettem a kód komplexitást, és érthetőbbé tettem a kódot, ahogy megbeszéltük. Egy fontosabb TODO maradt (https://github.com/Mikhus/domurl/issues/49), arra ha van időd, nézz rá te is kérlek @AnKa0

**Comment by AnKa0** [comment]
A manuális kód átvizsgálásnak nyitottam egy másik issue-t (#12).
