### ISSUE TITLE
Manuális kód átvizsgálás

### ISSUE THREAD

**Issue by AnKa0** [BME-MIT-IET/iet-hf2021-heekk#12]

**Comment by AnKa0** [comment]
@BME-MIT-IET/heekk  milyennek találtátok a kódot tesztelés szempontjából? Könnyű volt tesztelni, debugolni? Hibák javítása esetén egyszerű volt megtalálni a hiba okát?

**Comment by rhalm** [comment]
Szerintem nehezen érthető volt, például sok helyen a változónevek csak 1-2 karakter hosszúak voltak, és nem volt mellé magyarázat. Ezeket próbáltam javítani és érthetőbbé tenni a #4-es pull request-ben.

**Comment by AnKa0** [comment]
> Szerintem nehezen érthető volt, például sok helyen a változónevek csak 1-2 karakter hosszúak voltak, és nem volt mellé magyarázat. Ezeket próbáltam javítani és érthetőbbé tenni a #4-es pull request-ben.

Igen, ez nekem is feltűnt.

**Comment by Menci77** [comment]
Egyet értek én is. A függvényekben számos olyan lépés volt, ami nem egyértelmű pl.decode függvény és a magyarázó kommentek hiányoztak.

**Comment by AnKa0** [comment]
@BME-MIT-IET/heekk  szeretnék review-t kérni  erre az issue-ra

**Comment by Balint-Jeszenszky** [comment]
> @BME-MIT-IET/heekk szeretnék review-t kérni erre az issue-ra

nekem megfelel

**Comment by edvig** [comment]
> @BME-MIT-IET/heekk szeretnék review-t kérni erre az issue-ra

mehet részemről is
