### ISSUE TITLE
Manuális tesztek megtervezése, végrehajtása és dokumentálása

### ISSUE THREAD

**Issue by rhalm** [BME-MIT-IET/iet-hf2021-heekk#8]

**Comment by edvig** [comment]
Safariban való tesztelést vállalom.

**Comment by Menci77** [comment]
Chrome-ban tesztelést csinálom én.

**Comment by Menci77** [comment]
98c9b316db4b2da3d852dabb7113f20d6dc6244a

**Comment by Menci77** [comment]
Added chrome tests and modified IET-HF documentation
70f7aa59088f2f3dd48e89d0594a710597a1146d

**Comment by Menci77** [comment]
Added more tests for Chrome
57aad0f508d3210decd71873615ac7462eecc7ad

**Comment by edvig** [comment]
Safari tests 752a66d5b800697853397409b644e5c945eaf05e

**Comment by rhalm** [comment]
Firefox-ban való tesztelést csinálom.

**Comment by AnKa0** [comment]
Opera-ban való tesztelést vállalom

**Comment by AnKa0** [comment]
url.html-es tesztek és dokumentáció 4c6edcf
